export const uiText = {
  sidebar: {
    feed: 'Feed',
    wall: 'Wall',
    chat: 'Chat',
    tasks: 'Tasks',
    pamm: 'PAMM',
    documents: 'Documents',
    calendar: 'Calendar',
    events: 'Events',
    employees: 'Employees',
    notifications: 'Notifications',
    dashboard: 'Dashboard',
    adminPanel: 'Admin Panel',
  },

  common: {
    open: 'Open',
    download: 'Download',
    delete: 'Delete',
    save: 'Save',
    create: 'Create',
    update: 'Update',
    close: 'Close',
    loading: 'Loading...',
    noActiveUser: 'No active user.',
    untitled: 'Untitled',
    user: 'User',
    noData: 'No data yet.',
    back: 'Back',
    submit: 'Submit',
    cancel: 'Cancel',
    edit: 'Edit',
    remove: 'Remove',
  },

  login: {
    title: 'Welcome back',
    subtitle: 'Sign in to access RCX Network.',
    email: 'Email',
    password: 'Password',
    signIn: 'Sign in',
    signingIn: 'Signing in...',
    invalidCredentials: 'Invalid email or password.',
  },

  announcement: {
    pinned: 'Pinned announcement',
    until: 'Until',
    title: 'Pinned announcement',
    subtitle:
      'This message appears at the top for all users until you remove it or it expires.',
    placeholder:
      'Example: The office will close at 3 PM tomorrow. Or: Team event starts at 6 PM today.',
    expiresAt: 'Expires at (optional)',
    saved: 'Pinned announcement saved.',
    savePin: 'Publish pin',
    updatePin: 'Update pin',
    removePin: 'Remove pin',
    saving: 'Saving...',
    removing: 'Removing...',
    enterContent: 'Please enter announcement content.',
  },

  popup: {
    newNotification: 'New notification',
    open: 'Open',
    close: 'Close',
  },

  feed: {
    title: 'Feed',
    subtitle:
      'The shared company feed for messages, files, likes, comments, and live updates.',
    newPostTitle: 'New post in Feed',
    newPostSubtitle:
      'A shared space for announcements, files, and quick updates.',
    placeholder: 'Write something to the team...',
    publish: 'Publish',
    publishing: 'Publishing...',
    writeOrChoose: 'Write something or choose a file.',
    noPosts: 'No feed posts yet.',
    likes: 'likes',
    comments: 'comments',
    like: 'Like',
    liked: 'Liked',
    commentsTitle: 'Comments',
    noComments: 'No comments yet.',
    writeComment: 'Write a comment...',
    addComment: 'Add comment',
    attachedFile: 'Attached file',
    openFile: 'Open file',
    downloadFile: 'Download',
  },

  chat: {
    title: 'Chat',
    subtitle: 'Direct messages with anyone in the company.',
    roomSubtitle: 'Direct message conversation.',
    openChat: 'Open chat',
    opening: 'Opening...',
    noUsers: 'No users found.',
    noJobTitle: 'No job title',
    noDepartment: 'No department',
    online: 'Online',
    offline: 'Offline',
    typing: 'is typing...',
    seen: 'Seen',
    sent: 'Sent',
    newMessage: 'New message',
    writeMessage: 'Write a message... (Enter = send, Shift+Enter = new line)',
    send: 'Send',
    sending: 'Sending...',
    writeOrChoose: 'Write a message or choose a file.',
    openAttached: 'Open attached file',
    you: 'You',
  },

  tasks: {
    title: 'Tasks',
    subtitle: 'Manage assigned tasks and track their status.',
    newTask: 'New task',
    newTaskTitle: 'New task',
    newTaskSubtitle: 'Create a task and assign it to an employee.',
    selectEmployee: 'Select employee',
    titlePlaceholder: 'Title',
    descriptionPlaceholder: 'Description',
    low: 'Low priority',
    medium: 'Medium priority',
    high: 'High priority',
    createTask: 'Create task',
    saving: 'Saving...',
    fillRequired: 'Please fill in the title and choose an employee.',
    noTasks: 'No tasks.',
    total: 'Total tasks',
    new: 'New',
    inProgress: 'In progress',
    done: 'Done',
    assignedTo: 'Assigned to',
    dueDate: 'Due date',
    noDueDate: 'None',
    changeStatus: 'Change status',
    deleteTask: 'Delete task',
    statusNew: 'New',
    statusInProgress: 'In progress',
    statusDone: 'Done',
  },

  pamm: {
    title: 'PAMM',
    subtitle:
      'Shared items visible to everyone, with live updates and notifications.',
    newItem: 'New PAMM item',
    newItemTitle: 'New PAMM item',
    newItemSubtitle: 'Create a shared PAMM item visible to everyone.',
    titlePlaceholder: 'Title',
    descriptionPlaceholder: 'Description',
    amountPlaceholder: 'Amount',
    create: 'Create PAMM item',
    saving: 'Saving...',
    noItems: 'No PAMM items yet.',
    total: 'Total items',
    new: 'New',
    inProgress: 'In progress',
    done: 'Done',
    createdBy: 'Created by',
    date: 'Date',
    updateStatus: 'Update status',
    delete: 'Delete',
    enterTitle: 'Please enter a title.',
    enterAmount: 'Please enter a valid amount.',
  },

  documents: {
    title: 'Documents',
    subtitle: 'Company sections and documents for viewing and downloading.',
    newCompany: 'New company',
    newCompanySubtitle: 'Add a new company to the Documents section.',
    companyNamePlaceholder: 'Company name',
    addCompany: 'Add',
    adding: 'Saving...',
    noCompanies: 'No companies added yet.',
    openSection: 'Open documents section',
    deleteCompany: 'Delete company',
    companyDocumentsSubtitle: 'Documents for the selected company.',
    newDocument: 'New document',
    newDocumentSubtitle: 'Upload a document to this company.',
    documentNamePlaceholder: 'Document name',
    uploadDocument: 'Upload document',
    uploading: 'Uploading...',
    noDocuments: 'No documents uploaded yet.',
    addedOn: 'Added on',
    enterCompany: 'Please enter a company name.',
    enterDocument: 'Please enter a document title and choose a file.',
  },

  admin: {
    title: 'Admin Panel',
    subtitle:
      'Manage users, pinned announcements, and company data from one place.',
    users: 'Users',
    posts: 'Posts',
    tasks: 'Tasks',
    eventsChats: 'Events / Chats',
    newTask: 'New task',
    newEvent: 'New event',
    saveChanges: 'Save changes',
    openProfile: 'Open profile',
    name: 'Name',
    role: 'Role',
    jobTitle: 'Job title',
    department: 'Department',
    phone: 'Phone',
    avatarUrl: 'Avatar URL',
    bio: 'Bio',
    noName: 'No name',
  },

  employees: {
    title: 'Employees',
    subtitle: 'Larger cards and avatars so everyone is easier to recognize.',
    noEmployees: 'No employees added yet.',
    noJobTitle: 'No job title',
    noDepartment: 'No department',
    noName: 'No name',
    profileTitle: 'Employee profile',
    contact: 'Contact',
    about: 'About',
  },

  dashboard: {
    title: 'Dashboard',
    subtitle: 'Overview of activity, workload, and current company status.',
    totalEmployees: 'Total employees',
    totalPosts: 'Total posts',
    openTasks: 'Open tasks',
    upcomingEvents: 'Upcoming events',
    recentActivity: 'Recent activity',
    noRecentActivity: 'No recent activity yet.',
  },

  events: {
    title: 'Events',
    subtitle: 'Company events, attendance, and upcoming plans.',
    newEvent: 'New event',
    newEventTitle: 'Create event',
    newEventSubtitle: 'Publish a new company event for everyone.',
    noEvents: 'No events yet.',
    location: 'Location',
    date: 'Date',
    time: 'Time',
    description: 'Description',
    titleField: 'Event title',
    locationField: 'Event location',
    dateField: 'Event date',
    timeField: 'Event time',
    descriptionField: 'Event description',
    createEvent: 'Create event',
    creating: 'Creating...',
    fillRequired: 'Please fill in the title, date, and time.',
    attend: 'I will attend',
    decline: 'I will not attend',
    responseSaved: 'Your response has been saved.',
    attending: 'Attending',
    notAttending: 'Not attending',
  },

  wall: {
    title: 'Wall',
    subtitle: 'Project posts, updates, reviews, and shared work progress.',
    newPostTitle: 'New wall post',
    newPostSubtitle: 'Share project progress, files, and updates.',
    placeholder: 'Write your project update...',
    publish: 'Publish',
    publishing: 'Publishing...',
    noPosts: 'No wall posts yet.',
    reviewed: 'Reviewed',
    markReviewed: 'Mark as reviewed',
    status: 'Status',
    inProgress: 'In progress',
    completed: 'Completed',
    pending: 'Pending',
    comments: 'Comments',
    addComment: 'Add comment',
    writeComment: 'Write a comment...',
    writeOrChoose: 'Write a post or choose a file.',
  },

  notifications: {
    title: 'Notifications',
    subtitle: 'All your latest alerts in one place.',
    noNotifications: 'No notifications yet.',
    markRead: 'Mark as read',
    unread: 'Unread',
    read: 'Read',
  },
} as const