export const uiText = {
  sidebar: {
    feed: 'Feed',
    wall: 'Wall',
    chat: 'Chat',
    tasks: 'Tasks',
    pamm: 'PAMM',
    documents: 'Documents',
    calendar: 'Calendar',
    events: 'Events',
    employees: 'Employees',
    notifications: 'Notifications',
    dashboard: 'Dashboard',
    adminPanel: 'Admin Panel',
  },

  common: {
    open: 'Open',
    download: 'Download',
    delete: 'Delete',
    save: 'Save',
    create: 'Create',
    update: 'Update',
    close: 'Close',
    loading: 'Loading...',
    noActiveUser: 'No active user.',
    untitled: 'Untitled',
    user: 'User',
    noData: 'No data yet.',
    back: 'Back',
  },

  login: {
    title: 'Welcome back',
    subtitle: 'Sign in to continue to RCX Network.',
    email: 'Email',
    password: 'Password',
    signIn: 'Sign in',
    signingIn: 'Signing in...',
    invalidCredentials: 'Invalid email or password.',
  },

  feed: {
    title: 'Feed',
    subtitle:
      'The shared company feed for messages, files, likes, comments, and live updates.',
    newPostTitle: 'New post in Feed',
    newPostSubtitle:
      'Share an announcement, update, file, or quick message with everyone.',
    placeholder: 'Write something for the team...',
    publish: 'Publish',
    publishing: 'Publishing...',
    writeOrChoose: 'Write something or choose a file.',
    noPosts: 'No feed posts yet.',
    likes: 'likes',
    comments: 'comments',
    like: 'Like',
    liked: 'Liked',
    commentsTitle: 'Comments',
    noComments: 'No comments yet.',
    writeComment: 'Write a comment...',
    addComment: 'Add comment',
    attachedFile: 'Attached file',
    openFile: 'Open file',
    downloadFile: 'Download',
  },

  wall: {
    title: 'Wall',
    subtitle: 'Project reports, work updates, and progress posts.',
    newPostTitle: 'New report / project post',
    newPostSubtitle:
      'Create a work report or project update and share your progress.',
    placeholder: 'Write your report or project update...',
    publish: 'Publish',
    publishing: 'Publishing...',
    writeOrChoose: 'Write a report/project update or choose a file.',
    noPosts: 'No wall posts yet.',
    reviewed: 'Reviewed',
    markReviewed: 'Mark as reviewed',
    status: 'Status',
    inProgress: 'In progress',
    completed: 'Completed',
    pending: 'Pending',
    comments: 'Comments',
    addComment: 'Add comment',
    writeComment: 'Write a comment...',
    openFile: 'Open file',
    downloadFile: 'Download',
  },

  calendar: {
    title: 'Calendar',
    subtitle: 'Your schedule with tasks and events in one place.',
    noItems: 'Nothing is scheduled yet.',
    tasks: 'Tasks',
    events: 'Events',
    date: 'Date',
    dueDate: 'Due date',
  },

  events: {
    title: 'Events',
    subtitle: '✨ Company events, plans, and attendance in one place.',
    newEvent: '➕ New event',
    noEvents: 'No events yet.',
    location: '📍 Location',
    date: '📅 Date',
    time: '⏰ Time',
    description: '📝 Description',
    attend: '✅ I will attend',
    decline: '❌ I will not attend',
    attending: '✅ Attending',
    notAttending: '❌ Not attending',
  },
} as const