export const uiText = {
  sidebar: {
    feed: 'Feed',
    wall: 'Wall',
    chat: 'Chat',
    tasks: 'Tasks',
    pamm: 'PAMM',
    documents: 'Documents',
    calendar: 'Calendar',
    events: 'Events',
    employees: 'Employees',
    notifications: 'Notifications',
    dashboard: 'Dashboard',
    adminPanel: 'Admin Panel',
  },

  common: {
    open: 'Open',
    download: 'Download',
    delete: 'Delete',
    save: 'Save',
    create: 'Create',
    update: 'Update',
    close: 'Close',
    loading: 'Loading...',
    noActiveUser: 'No active user.',
    untitled: 'Untitled',
    user: 'User',
  },

  announcement: {
    pinned: 'Pinned announcement',
    until: 'Until',
  },

  popup: {
    newNotification: 'New notification',
    open: 'Open',
    close: 'Close',
  },

  feed: {
    title: 'Feed',
    subtitle:
      'The shared company feed for messages, files, likes, comments, and live updates.',
    newPostTitle: 'New post in Feed',
    newPostSubtitle:
      'A shared space for announcements, files, and quick updates.',
    placeholder: 'Write something to the team...',
    publish: 'Publish',
    publishing: 'Publishing...',
    writeOrChoose: 'Write something or choose a file.',
    noPosts: 'No feed posts yet.',
    likes: 'likes',
    comments: 'comments',
    like: 'Like',
    liked: 'Liked',
    commentsTitle: 'Comments',
    noComments: 'No comments yet.',
    writeComment: 'Write a comment...',
    addComment: 'Add comment',
    attachedFile: 'Attached file',
    openFile: 'Open file',
    downloadFile: 'Download',
  },

  chat: {
    title: 'Chat',
    subtitle: 'Direct messages with anyone in the company.',
    roomSubtitle: 'Direct message conversation.',
    openChat: 'Open chat',
    opening: 'Opening...',
    noUsers: 'No users found.',
    noJobTitle: 'No job title',
    noDepartment: 'No department',
    online: 'Online',
    offline: 'Offline',
    typing: 'is typing...',
    seen: 'Seen',
    sent: 'Sent',
    newMessage: 'New message',
    writeMessage: 'Write a message... (Enter = send, Shift+Enter = new line)',
    send: 'Send',
    sending: 'Sending...',
    writeOrChoose: 'Write a message or choose a file.',
    openAttached: 'Open attached file',
    you: 'You',
  },

  tasks: {
    title: 'Tasks',
    subtitle: 'Manage assigned tasks and track their status.',
    newTask: 'New task',
    newTaskTitle: 'New task',
    newTaskSubtitle: 'Create a task and assign it to an employee.',
    selectEmployee: 'Select employee',
    titlePlaceholder: 'Title',
    descriptionPlaceholder: 'Description',
    low: 'Low priority',
    medium: 'Medium priority',
    high: 'High priority',
    createTask: 'Create task',
    saving: 'Saving...',
    fillRequired: 'Please fill in the title and choose an employee.',
    noTasks: 'No tasks.',
    total: 'Total tasks',
    new: 'New',
    inProgress: 'In progress',
    done: 'Done',
    assignedTo: 'Assigned to',
    dueDate: 'Due date',
    noDueDate: 'None',
    changeStatus: 'Change status',
    deleteTask: 'Delete task',
    statusNew: 'New',
    statusInProgress: 'In progress',
    statusDone: 'Done',
  },

  pamm: {
    title: 'PAMM',
    subtitle: 'Shared items visible to everyone, with live updates and notifications.',
    newItem: 'New PAMM item',
    newItemTitle: 'New PAMM item',
    newItemSubtitle: 'Create a shared PAMM item visible to everyone.',
    titlePlaceholder: 'Title',
    descriptionPlaceholder: 'Description',
    amountPlaceholder: 'Amount',
    create: 'Create PAMM item',
    saving: 'Saving...',
    noItems: 'No PAMM items yet.',
    total: 'Total items',
    new: 'New',
    inProgress: 'In progress',
    done: 'Done',
    createdBy: 'Created by',
    date: 'Date',
    updateStatus: 'Update status',
    delete: 'Delete',
    enterTitle: 'Please enter a title.',
    enterAmount: 'Please enter a valid amount.',
  },

  documents: {
    title: 'Documents',
    subtitle: 'Company sections and documents for viewing and downloading.',
    newCompany: 'New company',
    newCompanySubtitle: 'Add a new company to the Documents section.',
    companyNamePlaceholder: 'Company name',
    addCompany: 'Add',
    adding: 'Saving...',
    noCompanies: 'No companies added yet.',
    openSection: 'Open documents section',
    deleteCompany: 'Delete company',
    companyDocumentsSubtitle: 'Documents for the selected company.',
    newDocument: 'New document',
    newDocumentSubtitle: 'Upload a document to this company.',
    documentNamePlaceholder: 'Document name',
    uploadDocument: 'Upload document',
    uploading: 'Uploading...',
    noDocuments: 'No documents uploaded yet.',
    addedOn: 'Added on',
    enterCompany: 'Please enter a company name.',
    enterDocument: 'Please enter a document title and choose a file.',
  },
} as const